openapi: 3.0.0
info:
  title: Example API
  description: This is an example API to demonstrate a GET and POST endpoint.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /items:
    get:
      summary: Get list of items
      operationId: get-items
      description: Retrieves a list of items.
      responses:
        '200':
          description: A list of items.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "Item 1"
                    description:
                      type: string
                      example: "This is item 1"
    post:
      summary: Create a new item
      operationId: create-item
      description: Creates a new item.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "New Item"
                description:
                  type: string
                  example: "Description of the new item"
      responses:
        '201':
          description: Item created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  name:
                    type: string
                    example: "New Item"
                  description:
                    type: string
                    example: "Description of the new item"
        '400':
          description: Bad request. Missing required fields or invalid input.
